// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emqnadrryrvswxhzgont.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcW5hZHJyeXJ2c3d4aHpnb250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTE0MjQsImV4cCI6MjA2NTc2NzQyNH0.8rvTHEBEQSmo4cSA1htRYwU4Q6yGo9Z4Psegz8HUOnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});